### ISSUE TITLE
希望能够选择是否只使用default音效

### ISSUE THREAD

**Issue by OniNezuko** [Milkitic/KeyASIO.Net#2]
在使用ORTDP的keyasio时，即使我勾选了忽略谱面音效，keyasio依旧会播放谱面音效而不是default的音效。在 [某些地图中](https://osu.ppy.sh/beatmapsets/1360892#osu/2815969) 会变的十分恼人。
是否能加一个选项，只使用default的音效，而不是优先选用谱面音效呢？

**Comment by Milkitic** [comment]
感谢反馈，这个功能在Todo列表中，近期会完善，正式版中也会包含。

**Comment by Milkitic** [comment]
Supported since v3.0.0-beta.4
