### ISSUE TITLE
在测试版本中，切换地图进行游玩会导致KeyASIO崩溃

### ISSUE THREAD

**Issue by OniNezuko** [Milkitic/KeyASIO.Net#3]
在程序崩溃前，osu会处于仍然在渲染但物件不动的情况 ;(

环境
Windows 10 IoT 企业版 LTSC 10.0.19044 Build 19044
osu声音输出设备为屏幕
ASIO声卡 Komplete Audio 2 @ 8 samples&44100Hz

**Comment by Milkitic** [comment]
可以的话贴一份log，在软件的logs/下

**Comment by Milkitic** [comment]
Fixed since v3.0.0-beta.10
